### ISSUE TITLE
building with Visual C++

### ISSUE THREAD

**Issue by neozeed** [lisper/emulator-sun-2#5]
I have been building with VC 2003 (Yes I know it's old, Im weird, but I have a legit version so ... Im using it!).  Anyways I submitted one pull for it's dislike for the way some variables are declared c++ like in the middle of the body.  No biggie.

I've also been able to build and link it to SLiRP so there is no need to do anything with tun/tap/bpf.  This way you can just redirect tcp ports as a user program into the VM.  Ive been able to paste 100kb worth of text, to uudecode and build a program on SunOS 2.0 from Windows 10.   I'll try to add a pull request although using github is all new and strange to me.

I'd like to add dynamic pcap support (I've done it for Basilisk II and Pcemu), along with UDP packet forwarding to get it to talk to things like GNS3 (virtual cisco routers!)  We could re-play the morris worm as SIMH's VAX support can do UDP forwarding as well, so it'd be cute to build an 'internet' on a desktop with a bunch of 4.2BSD Vaxen, and SunOS 2.0 SUN-2's

Also is it so bad to maybe split sim.c into a SDL/SDl2 path?  I kind of have some strange dislike of SDL2... maybe its the higher requirements, but I like preserving the older (simplier) code path, it could be a config option? or #define?

Sorry if I'm rambling too much

**Comment by sigurbjornl** [comment]
> On 24 Aug 2020, at 03:47, neozeed <notifications@github.com> wrote:
> 
> 
> I'd like to add dynamic pcap support (I've done it for Basilisk II and Pcemu), along with UDP packet forwarding to get it to talk to things like GNS3 (virtual cisco routers!) We could re-play the morris worm as SIMH's VAX support can do UDP forwarding as well, so it'd be cute to build an 'internet' on a desktop with a bunch of 4.2BSD Vaxen, and SunOS 2.0 SUN-2's
> 
The 3c400 emulation I hacked in is already using BPF, it shouldn't be very difficult to hack the pcap support into that, perhaps make it a configurable option so that the user can choose which to use.

I tested the 3c400 emulation with a VMware NetBSD machine I had running on my own machine at the same time, it worked fine, I was even able to mount a NFS filesystem to the SunOS machine from the NetBSD machine.

Kind regards,
Sibbi
